codeforIATI/iati-datastore

iati_datastore/iatilib/codelists/__init__.py
This is at least 10x faster, because the redirects are extremely slow.
=> Download codelists from new location

.gitignore, iati_datastore/docs_source/api/error.rst, iati_datastore/iatilib/frontend/api1.py
Shows the health status of the Datastore on the `/api/1/about` URL, e.g.:
```json
{
"indexed_activities": 473, 
"indexed_transactions": 5203, 
"ok": false, 
"status": "unhealthy", 
"status_data": {
"last_fetch": "Mon, 07 Dec 2020 18:48:22 GMT", 
"last_parsed": "Mon, 07 Dec 2020 18:48:47 GMT", 
"last_succ": "Mon, 07 Dec 2020 18:48:22 GMT"
}
}
```
=> Show health status

iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/frontend/routes.py, iati_datastore/iatilib/test/test_api.py
I’d like to easily be able to explore the API, via some sort of listings page. This adds that.
Apparently this is called [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS).
=> Add a base URL route

iati_datastore/iatilib/console.py, iati_datastore/iatilib/test/test_console.py
This now creates a migrations table, in the same way that `iati db upgrade` does.
Alternatively, we could scrap this command and just have `iati db upgrade` since it does exactly the same thing.
=> Remove `iati create-database`; Add confirmation prompt to `iati drop-database`

iati_datastore/iatilib/frontend/api1.py
Looks like this:
```json
[
"http://localhost:5000/api/1/",
"http://localhost:5000/api/1/about/",
"http://localhost:5000/api/1/about/dataset/",
"http://localhost:5000/api/1/about/dataset/DATASET/",
"http://localhost:5000/api/1/about/datasets/fetch_status/",
"http://localhost:5000/api/1/about/deleted/",
"http://localhost:5000/api/1/access/activity.FORMAT",
"http://localhost:5000/api/1/access/activity.FORMAT",
"http://localhost:5000/api/1/access/activity/by_country.FORMAT",
"http://localhost:5000/api/1/access/activity/by_sector.FORMAT",
"http://localhost:5000/api/1/access/budget.FORMAT",
"http://localhost:5000/api/1/access/budget/by_country.FORMAT",
"http://localhost:5000/api/1/access/budget/by_sector.FORMAT",
"http://localhost:5000/api/1/access/transaction.FORMAT", …
```
=> Fix base API route, so list of routes is clearer

README.md, iati_datastore/iatilib/crawler.py
After deployment, it’s important to update the `crawl_update.sh` script on the server, to point at the new command.
=> Use hyphens instead of underscores

iati_datastore/iatilib/crawler.py
180 seconds isn’t long enough for my slow internet connection!
=> Use correct `job_timeout` kwarg, and extend timeout for downloading data dump

iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/frontend/serialize/jsonserializer.py
This reverts IATI#317, because it broke CSV streaming.
I don’t think it’s broken on http://datastore.iatistandard.org, because I don’t think IATI#317 was ever deployed.
This PR addresses IATI#315 a slightly different way instead.
Fixes #175.
=> Get stream=True working for CSV and JSON

iati_datastore/iatilib/frontend/api1.py
Fixes #176.
This uses https://stackoverflow.com/a/7794516/2323348 to name one of the endpoints so it is distinct. Plus there is a bit of a hack to work around a default args issue (but I don’t think it is too hacky).
=> Fix routes listed at /api/1/

iati_datastore/query_builder_source/pages/index.vue
Fixes #160
Looks like this (tooltip appears when hovering over CSV options when CSV is not selected):
=> Add XML and JSON options to query builder

datastore.wsgi
I don’t think this is being used. (I think we’re using liveserver.py instead).
=> rm datastore.wsgi

iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/frontend/templates/dataset.log
https://datastore.codeforiati.org/api/1/error/dataset.log/aics-bo/
Is returning a 500 error currently, because logs are always expected to contain a traceback (which they don’t).
Also, I think these dataset.log routes should use `text/plain` mimetype.
=> Fix some issues with /api/1/error/dataset.log

iati_datastore/iatilib/frontend/api1.py
This route duplicates the /api/1/error/dataset/DATASET_ID/ route. It’s
also a bit confusing, because it’s the only route that requires a
parameter (`url`).
This is technically a breaking API change… But I think it’s probably
fine to do.
=> Drop /api/1/error/resource/ route

iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/test/test_api.py
This removes the call to `query.count()` from CSV responses, since it can be very slow, and the result is never actually used.
Refs #80.
=> Speed up CSV responses a bit

iati_datastore/iatilib/frontend/api1.py
This PR changes the behaviour when `stream=false`, so that the response is served as soon as it’s available.
So for example:
https://datastore.codeforiati.org/api/1/access/activity.csv?limit=1000
Without this PR, there’s a long initial delay to compute this response, and then the whole thing is served at once.
With this PR, the initial response is served as soon as it’s available, and then the remainder is served in batches. I think this ought to be less memory-intensive.
=> Stream even non-streaming requests

iati_datastore/iatilib/frontend/api1.py
I don’t quite understand why this is necessary, but it seems to fix sqlalchemy errors.
=> Stream with context

iati_datastore/iatilib/frontend/api1.py
We shouldn’t be calling `.all()`.
This is an addendum to #221.
=> Avoid loading everything up front (addendum to #221)

iati_datastore/iatilib/crawler.py, iati_datastore/iatilib/test/test_crawler.py
Refs #62. Adds a command line option to allow hashes to be ignored, in order to trigger a full reimport of data.
=> Allow full reimport, by ignoring hashes

iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/test/test_api.py
`total` is expensive, so it should only be called when it’s used.
Fixes #235, I think.
=> Change how scrollination works

iati_datastore/iatilib/frontend/api1.py, iati_datastore/query_builder_source/pages/index.vue
This will also be displayed on the query builder interface, like this:
If you hover over the % complete, it tells you the number of jobs left and the total number of datasets.
=> Show number of jobs left on the queue

iati_datastore/iatilib/crawler.py
This might help to address memory problems that occur when large numbers of datasets (and their corresponding activities) need to be deleted.
=> Delete datasets one at a time

iati_datastore/iatilib/frontend/serialize/csv.py, iati_datastore/iatilib/test/test_serializers/test_csv_budgets.py
Budget type can sometimes be None. In this case, it will have no Name.
=> Fix budget type bug, fixes #259

iati_datastore/setup.py, requirements.txt
This new version points to s3 for the IATI data zip file.
=> Upgrade to the latest version of iatikit

fabfile.py, iati_datastore/iatilib/console.py, iati_datastore/iatilib/test/test_console.py
Use `npm ci` rather than `npm i` to avoid editing `package-lock.json` on deployment
=> Fix deployment using npm ci

iati_datastore/query_builder_source/nuxt.config.js
Add trailing slash to routes to avoid 404ing on `/fr`
=> Add trailing slash to routes

fabfile.py
Now that we’re using npm ci, I don’t think this is necessary anymore.
=> Remove git checkout from fabfile

iati_datastore/setup.py
Update setup.py in line with requirements.txt change
made in 56df2ebcb6504f1db0842fd0ac2f34b553bbcfbc
Should have been updated at the same time!
=> docs: Lock to earlier version of docutils to avoid a bug

iati_datastore/setup.py, requirements.txt
This version of iatikit will throw a FileNotFoundError if `dataset.raw_xml` is called for a missing dataset (i.e. a dataset for which we have metadata but no data, presumably because data download failed).
This will be caught here: https://github.com/codeforIATI/iati-datastore/blob/00127ff054e80ff2e0127fe6f7eff3ebb892ed81/iati_datastore/iatilib/crawler.py#L126-L128
This still isn’t really ideal… But the previous version of iatikit threw a TypeError, which was even more weird.
=> Update iatikit to 3.3.0

.gitignore, README.md, fabfile.py, iati_datastore/iatilib/babel.cfg, iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/frontend/app.py, iati_datastore/iatilib/frontend/serialize/babel.py, iati_datastore/iatilib/frontend/serialize/csv.py, iati_datastore/iatilib/test/__init__.py, iati_datastore/iatilib/test/test_serializers/__init__.py, iati_datastore/iatilib/test/test_serializers/test_csv_activities.py, iati_datastore/iatilib/test/test_serializers/test_csv_budgets.py, iati_datastore/iatilib/test/test_serializers/test_csv_transactions.py, iati_datastore/iatilib/translations/fr/LC_MESSAGES/messages.po, iati_datastore/iatilib/translations/pt/LC_MESSAGES/messages.po, iati_datastore/query_builder_source/pages/index.vue, iati_datastore/setup.py, requirements.txt, requirements_dev.txt
https://github.com/codeforIATI/iati-datastore/issues/341
=> i18n: Add locale key to API and start translating CSV/XLSX headers

iati_datastore/setup.py, requirements.in, requirements.txt, requirements_dev.txt
Refs https://github.com/codeforIATI/iati-data-dump/issues/6#issuecomment-1225562386
iatikit now reads the download location from https://iati-data-dump.codeforiati.org/download, so we can more easily change it.
=> Upgrade iatikit to v3.3.1

iati_datastore/iatilib/currency_conversion.py, iati_datastore/iatilib/test/test_conversion.py
Includes cache key with date added, both to make tests work (using different key as data is different) and so cache expires after 24 hours
=> Cache currency conversion table for performance reasons

iati_datastore/iatilib/parse.py, iati_datastore/iatilib/test/fixtures/activity_with_empty_participating_org_narrative.xml, iati_datastore/iatilib/test/test_parser_bugs.py
Handles the case where participating organisation narratives are sometimes empty. Adds an additional test file to test for unusual bugs like this.
Fixes #404
=> Organisation narratives can sometimes be empty

.github/workflows/ci.yml
I'm going to have to upgrade our hosting to running in docker containers, so that we can keep running on the version of Python we need while allowing us to upgrade Ubuntu. Under these conditions and considering recent usage, keeping the continuous deployment going is too much work.
=> Remove Deploying from GitHub
