codeforIATI/iati-datastore

iati_datastore/docs_source/user-guide/how-is-the-csv-data-displayed.rst, iati_datastore/docs_source/user-guide/selecting-data-for-csv-output.rst, iati_datastore/docs_source/user-guide/tips-pitfalls-and-warnings.rst
=> Make nice warning and notes boxes

iati_datastore/iatilib/crawler.py
=> Set User-Agent header

iati_datastore/iatilib/frontend/api1.py
Make fewer database calls and tidy up code
=> Tweaks to health status code

README.md, iati_datastore/docs_source/index.rst, iati_datastore/setup.py
* Update README language
* Add nginx configuration instructions to README
* Update version in  `setup.py`
* Update some documentation
=> Update README and docs

fabfile.py, iati_datastore/setup.py, requirements_dev.txt
So to use this, you’ll need to:
```
pip install -r requirements_dev.txt
```
…and then:
```
fab deploy -H user@ip_address
```
…where `user@ip_address` contains the ssh credentials for connecting to the server.
=> Update the fabric deploy command

iati_datastore/iatilib/console.py, iati_datastore/query_builder_source/pages/index.vue
Make sure query builder dependencies are installed
=> Query builder tweaks

fabfile.py, iati_datastore/query_builder_source/layouts/default.vue
Update fabfile to ensure that the `deploy-url` is specified, and update footer.
=> Query builder tweaks (2)

iati_datastore/query_builder_source/nuxt.config.js, iati_datastore/query_builder_source/pages/index.vue
Make query builder build as a universal / static site rather than client-only
=> Query builder tweaks (3)

iati_datastore/query_builder_source/pages/index.vue
apiURL should be updated depending on computed baseURL
=> Query Builder tweaks (4)

iati_datastore/query_builder_source/layouts/default.vue, iati_datastore/query_builder_source/pages/index.vue
Fix typos and adjust footer text
=> Query builder tweaks (5)

iati_datastore/iatilib/frontend/app.py, iati_datastore/iatilib/frontend/builder.py
=> Turns an API request into a query builder request

iati_datastore/iatilib/frontend/api1.py
Relax health data, because it's all downloaded in bulk from iati data dump
=> Hotfix health warning

iati_datastore/iatilib/crawler.py, iati_datastore/iatilib/test/test_crawler.py
fetch_resource was erroring when data file was missing.
=> Fix fetch_resource bug

iati_datastore/iatilib/queue.py
=> Fix dataset and resource in error logs

iati_datastore/iatilib/crawler.py, iati_datastore/iatilib/parse.py
Set appropriate fallbacks for lists, fixes #152
=> Fix parse error logs

iati_datastore/docs_source/user-guide/support.rst
=> Fix links in support section of docs

iati_datastore/iatilib/crawler.py
Per this answer: https://stackoverflow.com/a/18244144/2323348
Fixes #163.
=> Create or update deleted activities

iati_datastore/docs_source/api.rst, iati_datastore/iatilib/frontend/dsfilter.py, iati_datastore/iatilib/frontend/validators.py, iati_datastore/iatilib/test/test_filter.py, iati_datastore/query_builder_source/pages/index.vue
Fixes #66, need to adjust when implementing #167
=> Add title and description filters

iati_datastore/query_builder_source/pages/index.vue
Fixes #174. I dunno if there’s a nicer way to do it – please feel free to close this and do it a nicer way!
=> Fix stream=True query builder issue

iati_datastore/iatilib/crawler.py, iati_datastore/iatilib/test/test_crawler.py
=> Don’t raise IndexErrors during crawl

.github/workflows/ci.yml
=> Deploy from a github action

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Add some issue templates

iati_datastore/iatilib/model.py, iati_datastore/iatilib/test/__init__.py, iati_datastore/iatilib/test/test_model.py, migrations/versions/120ee2333afe_.py
=> Attempt at tackling stats table issue

iati_datastore/iatilib/console.py, iati_datastore/iatilib/model.py
=> CLI command for resetting stats; Add comment about stats table updating

iati_datastore/iatilib/crawler.py
Bug fix – resource should be added to the session after amending.
Fixes #64.
=> Make sure last_parse_error gets saved

iati_datastore/iatilib/config.py, iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/frontend/validators.py
=> Paginate /about/deleted/

error/404.html, error/5xx.html
=> Add some basic error pages

iati_datastore/iatilib/frontend/templates/error/404.html, iati_datastore/iatilib/frontend/templates/error/5xx.html, iati_datastore/iatilib/frontend/templates/error/invalid_filter.html, iati_datastore/query_builder_source/layouts/default.vue
=> Fix nav markup, so brand logo doesn’t jump

README.md
I don’t know if this is too specific for the README, but I’m just conscious that this config sits outside of version control.
=> Update README with latest nginx config

iati_datastore/iatilib/model.py
See: https://stackoverflow.com/a/15542046/2323348
=> Fix application context bug

iati_datastore/iatilib/frontend/api1.py
=> Compute total-count before paginating

iati_datastore/iatilib/frontend/serialize/jsonserializer.py, iati_datastore/iatilib/test/test_serializers/test_json.py
=> Make JSON streaming for stream=True

iati_datastore/docs_source/api.rst, iati_datastore/iatilib/frontend/validators.py
Fixes #58.
This is maybe a bit controversial, so have a look at #58 and #29, and let me know if you’re happy with it!
=> Decrease non-streaming query limit to 1000

iati_datastore/iatilib/crawler.py, iati_datastore/iatilib/test/test_crawler.py
=> Key datasets on id, not (publisher_id, id)

iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/frontend/validators.py, iati_datastore/iatilib/test/test_api.py
=> Merge fetch_status into /api/1/about/dataset/

iati_datastore/docs_source/api.rst, iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/frontend/serialize/__init__.py, iati_datastore/iatilib/frontend/serialize/csv.py, iati_datastore/iatilib/frontend/serialize/jsonserializer.py, iati_datastore/iatilib/frontend/validators.py, iati_datastore/iatilib/test/test_serializers/test_json.py, iati_datastore/iatilib/test/test_serializers/test_xml_activities.py
Fixes #232.
~Incomplete – this still needs a couple of tests, and some documentation.~
=> Add an unwrap param

README.md, iati_datastore/query_builder_source/pages/index.vue
* Show last updated as hours / minutes / seconds ago
* Make the loading message nicer
=> Show clearer information about when the Datastore was last updated

iati-datastore_uwsgi.ini, iati_datastore/iatilib/config.py
=> Attempt to handle database disconnects

iati_datastore/iatilib/frontend/serialize/csv.py, iati_datastore/iatilib/test/test_serializers/test_csv_budgets.py, iati_datastore/setup.py, requirements.txt
=> Add budget type to budget CSV output

iati_datastore/query_builder_source/layouts/default.vue
=> Add welcome notice and Code for IATI sidebar

iati_datastore/docs_source/api.rst, iati_datastore/iatilib/frontend/dsfilter.py, iati_datastore/iatilib/frontend/validators.py, iati_datastore/iatilib/test/test_filter.py, iati_datastore/query_builder_source/pages/index.vue
=> Add activity status filter

iati_datastore/query_builder_source/pages/index.vue
=> Add option to return a single row

iati_datastore/query_builder_source/layouts/default.vue
Remove sidebar and revert navbar-brand for now to fix dropdown bugs, fixes #211
=> Fix dropdown bugs, removing sidebar temporarily

iati_datastore/iatilib/console.py, iati_datastore/iatilib/wsgi.py, iati_datastore/setup.py, requirements.txt
https://github.com/codeforIATI/iati-datastore/issues/275
=> Add Sentry

iati_datastore/query_builder_source/layouts/default.vue
Adds link to the Code for IATI Privacy Policy, for collecting analytics using Matomo.
Refs #269
=> Add privacy policy

.github/workflows/ci.yml, fabfile.py
This puts back what commit 2b5cd33fefa90d2b24aabbee7b6aa2cc602bcfd8
removed
=> Add Continuous Deployment

iati_datastore/iatilib/frontend/serialize/jsonserializer.py, iati_datastore/iatilib/test/test_serializers/test_json.py
=> Prevent JSON serializer from stripping whitespace

iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/frontend/dsfilter.py
Performance boost to /api/1/access/activity.csv
=> CSV download: Eager load joined tables

iati_datastore/query_builder_source/layouts/default.vue
Per the (brand new!) functionality and instructions here: https://codeforiati.org/sidebar/
=> Move the C4I sidebar to the right-hand side

iati_datastore/iatilib/frontend/api1.py, iati_datastore/query_builder_source/pages/index.vue
=> Add ?ref=qb to query builder generated URLs

iati_datastore/iatilib/codelists/__init__.py
Depends on codeforIATI/codelists#109.
=> Fetch v1 codelists from the codeforIATI API

iati_datastore/query_builder_source/lang/en.json, iati_datastore/query_builder_source/lang/fr.json
=> NumDatasets -> numDatasets

iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/frontend/serialize/csv.py
Use BytesIO rather than creating a temporary file
=> Use BytesIO rather than creating a temporary file

iati_datastore/iatilib/console.py, iati_datastore/iatilib/frontend/api1.py, iati_datastore/iatilib/frontend/serialize/__init__.py, iati_datastore/iatilib/frontend/serialize/csv.py, iati_datastore/iatilib/test/test_api.py, iati_datastore/openpyxl_copy/utils/__init__.py, iati_datastore/openpyxl_copy/utils/cell.py, iati_datastore/setup.py, requirements.txt, requirements_dev.txt
* /access/activity.xlsx
* /access/activity/by_country.xlsx
=> Add XLSX downloads

iati_datastore/query_builder_source/lang/en.json, iati_datastore/query_builder_source/lang/fr.json, iati_datastore/query_builder_source/lang/pt.json, iati_datastore/query_builder_source/pages/index.vue, requirements.txt
=> Add DS Classic video, add Excel download option, fix reset button

iati_datastore/iatilib/frontend/dsfilter.py
Performance boost to /api/1/access/transaction.csv
https://github.com/codeforIATI/iati-datastore/issues/346
=> Transaction download: Eager load joined tables

requirements.txt
To avoid backwards incompatible changes
=> requirements: Lock to an earlier versions

README.md
https://github.com/codeforIATI/iati-datastore/issues/298
=> vagrant: Update instructions on how to run tests

iati_datastore/iatilib/parse.py, iati_datastore/iatilib/test/test_parser.py
https://github.com/codeforIATI/iati-datastore/issues/34#issuecomment-1156317206
=> Organisation Role Mapping: Map V1 values to V2

iati_datastore/iatilib/frontend/dsfilter.py, iati_datastore/iatilib/frontend/validators.py, iati_datastore/iatilib/test/test_filter.py
https://github.com/codeforIATI/iati-datastore/issues/34
=> New filters: an participating organisation that is specifically funding/implementing etc.

iati_datastore/iatilib/frontend/dsfilter.py, iati_datastore/iatilib/test/test_filter.py
Search functionality for localised titles and descriptions, and across multiple description types, plus associated tests
=> Localised titles descriptions in csv - part2

.github/workflows/ci.yml
Set git email in deployment workflow to try to fix issue
=> Tweak workflow to try to fix deployment issue

.github/workflows/ci.yml
Put email in environment variable
=> Further tweak to workflow to try to fix deployment issue

.github/workflows/ci.yml
Add more details to environment variables
=> Another tweak to workflow to try to fix deployment issue

iati_datastore/iatilib/frontend/serialize/csv.py
https://github.com/codeforIATI/iati-datastore/issues/409
=> Catch ValueError, ignore
